---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Asia/Tokyo
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: friday
      time: "18:00"
      timezone: Asia/Tokyo
