---
name: Destroy exit nodes
concurrency: mnako/scaly-shark/destroy/${{ github.ref }}
"on":
  workflow_dispatch:
jobs:
  destroy:
    name: Destroy exit nodes
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v2.0.0
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Load 1Password Secrets
        uses: 1password/load-secrets-action@v2.0.0
        env:
          FLY_API_TOKEN:
            op://scaly-shark-secrets/FLY_API_TOKEN/credential
          TS_AUTH_KEY:
            op://scaly-shark-secrets/TS_AUTH_KEY/credential
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@63da3ecc5e2793b98a3f2519b3d75d4f4c11cec2
      - name: Destroy
        run: |
          make destroy
